defaults:
  - launcher: local
  - solver: cem
  - _self_

world:
  env_name: swm/DINOPointMaze-v0
  num_envs: ${eval.num_eval}
  max_episode_steps: ???
  camera_distance: 9.0
  camera_azimuth: 180.0
  success_threshold: 0.2
  show_target: false

dataset:
  stats: ${eval.dataset_name}
  keys_to_cache:
    - action
    - state

seed: 42
policy: random

plan_config:
  horizon: 5
  receding_horizon: 5
  action_block: 5

eval:
  source: dataset
  num_eval: 50
  goal_offset_steps: 25
  eval_budget: 100
  img_size: 224
  dataset_name: dino_pointmaze_expert_2000.lance
  callables:
    - method: _set_state
      args:
        state:
          value: state
    - method: _set_goal_state
      args:
        goal_state:
          value: goal_state

compile: false
bf16: false

output:
  filename: pointmaze_results.txt
