defaults:
  - lewm
  - _self_

output_model_name: detached_lewm
subdir: ${output_model_name}_${now:%Y-%m-%d_%H-%M-%S}
resume_from: null

rollout:
  horizon: 5
  sample_horizon: true
  weight: 1.0
  teacher_weight: 1.0

data:
  dataset:
    num_steps: ${eval:'${wm.history_size} + ${rollout.horizon}'}

trainer:
  max_epochs: 10
  max_steps: -1
  precision: bf16