defaults:
  - state_lewm
  - _self_

output_model_name: state_lewm_debug
subdir: ${output_model_name}

loader:
  batch_size: 2
  num_workers: 0
  persistent_workers: false
  prefetch_factor: null
  pin_memory: false

trainer:
  accelerator: cpu
  devices: 1
  precision: 32-true
  max_epochs: 2
  limit_train_batches: 2
  limit_val_batches: 1
  log_every_n_steps: 1
