defaults:
  - lewm
  - _self_
  - override data: maniskill_vision

output_model_name: vision_lewm
subdir: ${output_model_name}_${now:%Y-%m-%d_%H-%M-%S}
num_workers: 8
img_size: 128
patch_size: 8
encoder_scale: small

trainer:
  max_steps: -1
  max_epochs: 10
